"""
Purpose: Technical verification framework handling raw data normalization checks.
Protects application workflows from structural regressions and maps business policy designations.
"""

import logging
import json
from typing import Dict, Any, Tuple
from pydantic import ValidationError
from backend.models import InvestigationResultModel

logger = logging.getLogger("backend.utils")

def validate_llm_json_response(raw_string_payload: str) -> Tuple[bool, Dict[str, Any]]:
    """
    Validates that a string payload matches the strict schema definition contract while wiping artifacts.
    
    Args:
        raw_string_payload (str): Unparsed raw payload block data.
        
    Returns:
        Tuple[bool, Dict[str, Any]]: Verification status combined with normalized schema mapping dictionary.
    """
    try:
        parsed_dict = json.loads(raw_string_payload)
        
        # Normalize alternative keys generated by older model asset prompt steps
        normalized = {}
        normalized["fraud_score"] = parsed_dict.get("fraud_score") or parsed_dict.get("step_7_fraud_score")
        normalized["risk_level"] = parsed_dict.get("risk_level") or parsed_dict.get("step_5_risk_assessment")
        normalized["confidence"] = parsed_dict.get("confidence") or parsed_dict.get("step_8_confidence")
        normalized["recommendation"] = parsed_dict.get("recommendation") or parsed_dict.get("step_6_recommendation")
        normalized["reasoning"] = parsed_dict.get("reasoning") or parsed_dict.get("step_9_reasoning") or []
        normalized["fraud_indicators"] = parsed_dict.get("fraud_indicators") or parsed_dict.get("step_4_fraud_indicators") or []

        raw_summary = parsed_dict.get("investigation_summary")
        if not raw_summary:
            raw_summary = "The model did not return an investigation summary for this case; manual review of the raw output is recommended."
        normalized["investigation_summary"] = raw_summary

        # Keep the model's own policy_reference as-is: it only signals whether the model judged
        # policy guidance relevant. backend.investigator swaps this for the real retrieved
        # citations (or clears it) once it has that context - this function has no access to it.
        raw_policies = parsed_dict.get("policy_reference") or parsed_dict.get("step_3_policy_review", {}).get("policy_reference") or []
        normalized["policy_reference"] = raw_policies if isinstance(raw_policies, list) else [raw_policies]

        # A missing fraud_score means the LLM response was malformed - surface that instead of guessing.
        if normalized["fraud_score"] is None:
            return False, {"status": "error", "message": "LLM response did not include a fraud_score; cannot proceed without it."}
        if not normalized["risk_level"]:
            score = normalized["fraud_score"]
            normalized["risk_level"] = "High" if score >= 70 else ("Medium" if score >= 30 else "Low")
        # Missing confidence should read as uncertain, not as a confident "High" the model never stated.
        if not normalized["confidence"]:
            normalized["confidence"] = "Low"

        # Pydantic Enforcement Validation Check
        final_model = InvestigationResultModel.model_validate(normalized)
        return True, final_model.model_dump()
        
    except json.JSONDecodeError as err:
        logger.error(f"Malformed JSON intercepted structurally: {str(err)}")
        return False, {"status": "error", "message": f"Malformed payload structure: {str(err)}"}
    except ValidationError as err:
        logger.error(f"Schema mapping mismatch validation regression: {str(err)}")
        return False, {"status": "error", "message": f"Contract alignment exception: {str(err.errors())}"}
